### ISSUE TITLE
Uploaded SRS for review

### ISSUE THREAD

**Issue by KarenKarenWang** [KarenKarenWang/cas741_project1#3]
Dear Dr. @smiths :

I have uploaded my SRS, thanks for your review!

**Comment by smiths** [comment]
Thank you @KarenKarenWang.

**Comment by smiths** [comment]
@KarenKarenWang I'll provide more comments on your SRS, but for now I'll mention that it doesn't capture what we are trying to do.  Since it is relevant for your verification document, and it will help you improve your SRS, I did a quick POC program in Matlab.  You can find it in commit f170f84.  I think the names of the variables will be reasonably clear, but if you have any questions, let me know.  (If you don't have Matlab, you can install it through McMaster's site license.)

**Comment by smiths** [comment]
Comments on the SRS are available on a marked-up pdf in 7607810.
